#IBM 왓슨 빅데이터 과정 기말고사
### 일자 : 2021년 6월 9일

##이름 : 'YOUR NAME'

#문제 1 : Support Vector Machine(10점)
### sklearn의 Support Vector Machine API를 사용하여 iris dataset을 분석하는 코드입니다.
### your_code_here부분을 완성하십시오.

In [17]:
from sklearn.svm import SVC
import numpy as np
import matplotlib.pyplot as plt
from sklearn import svm, datasets

In [18]:
iris = datasets.load_iris()# Select 2 features / variables

###  datasets.load_iris()가 return해주는 값들에 대하여는 아래 링크를 참고하시오
https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_iris.html

In [19]:
print(iris.feature_names)
print(iris.target_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']


In [20]:
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [21]:
print(iris.data[0:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [22]:
print(iris.target[0:5])

[0 0 0 0 0]


##Q1-1. 데이터 전처리(3점)

In [30]:
X = iris.data[0:2] # iris.data 중 sepal length와 sepal width 두 개의 컬럼을 선택하여 slice한 후 변수X에 저정하는 코드를 입력하십시오.

###모델에 사용할 변수들을 다음과 같이 정의합니다.

In [24]:
y = iris.target
feature_names = iris.feature_names[:2]
classes = iris.target_names

## plot를 위한 함수들을 정의

In [25]:
def grid(x, y, h=.02):
    x_min, x_max = x.min() - 1, x.max() + 1
    y_min, y_max = y.min() - 1, y.max() + 1
    xx, yy = np.meshgrid(np.arange(x_min, x_max, h), np.arange(y_min, y_max, h))
    return xx, yy
def plot(ax, clf, xx, yy, **params):
    Z = clf.predict(np.c_[xx.ravel(), yy.ravel()])
    Z = Z.reshape(xx.shape)
    out = ax.contourf(xx, yy, Z, **params)
    return out

##Q1-2. Support Vector machine으로 Classifier 오브젝트를 생성하시오.(3점)

In [31]:
# Support Vector Machine을 사용하는 classifier를 model이라는 이름으로 생성시키는 코드를 입력하시오.
model = svm.SVC()

##Q1-3. 위에서 생성한 모델을 사용하여 트레이닝을 수행하시오.(4점)

In [ ]:
clf = X_train, X_test, Y_train, Y_test

### 결과를 plot

In [ ]:
fig, ax = plt.subplots()
# title for the plots
title = 'Decision Surface'
# Set-up grid for plotting.
X0, X1 = X[:, 0], X[:, 1]
xx, yy = grid(X0, X1)
plot(ax, clf, xx, yy, cmap=plt.cm.coolwarm, alpha=0.8)
ax.scatter(X0, X1, c=y, cmap=plt.cm.coolwarm, s=20, edgecolors="k")
ax.set_ylabel("{}".format(feature_names[0]))
ax.set_xlabel("{}".format(feature_names[1]))
ax.set_xticks(())
ax.set_yticks(())
ax.set_title(title)
plt.show()

#문제 2:Kmeans 클러스터링 코딩(10점)
### 다음은 Kmeans를 사용하는 코드입니다.  코드 중 your_code_here 부분을 완성하십시오. 

In [ ]:
## Import Library
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
from mpl_toolkits.mplot3d import Axes3D
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
import seaborn as sns
sns.set_theme(style="darkgrid")

In [ ]:
## 데이터 다운로드
! wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=1M-j_Fibx8Wq3IUzr1Nygab4VxEE0a7rn' -O Mall_Customers.csv 

In [ ]:
## Load Data
df = pd.read_csv("Mall_Customers.csv")
df = df[['Age','Annual Income (k$)']]
print('Total Row : ', len(df))
df.head()

In [ ]:
# scatter plot 출력
sns.relplot(x="Annual Income (k$)", y="Age", data=df)

## 위의 scatter plot을 보고 클러스터를 n 개로 하면 적절할지를 결정하시오.

In [ ]:
print('# of clusters k = n')

##Q2-1. 데이터프레임 df의 데이터를 StandScaler를 사용하여 정규화하십시오. 정규화된 데이터의 type은 float로 지정(힌트: astype(float) 사용)하십시오.(3점)

In [ ]:
## Feature Scaling
df_scaled = your_code_here

##Q2-2. df_scale에 대하여 KMeans 클러스터링을 수행하십시오.(3점)
참고 : https://scikit-learn.org/stable/modules/generated/sklearn.cluster.KMeans.html 

In [ ]:
## KMeans 클러스터링
kmeans = your_code_here

##Q2-3. 위의 결과로 각 데이터 포인트에 부여된 label의 값을 넘파이 어레이 labels에 저장하시오.(4점)

In [ ]:
labels = your_code_here

## 클러스터 별로 라벨링된 결과를 plot

In [ ]:
new_dfa = pd.DataFrame(data = df_scaled, columns = ['Age','Annual Income (k$)'])
new_dfa['label_kmeans'] = labels
fig, ax = plt.subplots(figsize=(10,7))
plt.scatter(new_dfa["Annual Income (k$)"][new_dfa["label_kmeans"] == 0], new_dfa["Age"][new_dfa["label_kmeans"] == 0], 
            color = "blue", s=100, edgecolor='green',linestyle='--')
plt.scatter(new_dfa["Annual Income (k$)"][new_dfa["label_kmeans"] == 1], new_dfa["Age"][new_dfa["label_kmeans"] == 1], 
            color = "red", s=100, edgecolor='green',linestyle='--')
plt.scatter(new_dfa["Annual Income (k$)"][new_dfa["label_kmeans"] == 2], new_dfa["Age"][new_dfa["label_kmeans"] == 2], 
            color = "green", s=100, edgecolor='green',linestyle='--')
centers = kmeans.cluster_centers_
plt.scatter(centers[:, 0], centers[:, 1], c='black', s=500);
ax.set_xlabel('Annual Income (k$)')
ax.set_ylabel('Age')
plt.show()

#문제3 : R Shiny 시각화 문제(10점)
### 다음 코드를 https://rstudio.cloud/ 에서 완성하여 수행하십시오.
### 아래의 이미지를 참조하여 동일한 UI 화면이 되도록 your_code_here부분을 완성하십시오.

In [ ]:
! wget --quiet --no-check-certificate 'https://docs.google.com/uc?export=download&id=1UB3bCm6JZozoHoHIYWOm9d6qiMnImjRV' -O shinyUI.jpg 
Image("shinyUI.jpg", width=500)

### 완성된 코드는 다시 아래 셀에 copy & paste하여 결과물로 제출해주십시오.(아래 셀에 완성된 코드를 제시하지 않으면 채점되지 않습니다.)

In [ ]:
# R Shiny 코드입니다. rstudio.com의 UI에 copy & paste하여 수정하십시오.
ui <- fluidPage(
    titlePanel("Sum"),
    #number input form
    sidebarLayout(
      sidebarPanel(
        #your_code_here(4점)
      ),
      
      # Show result
      mainPanel(
        h3("결과"),
        textOutput("sum")
      
      )
    )
  ) # fluidPage

  
  # Define server function  
  server <- function(input,output,session) {
    #observe the add click and perform a reactive expression
    observeEvent( input$add,{
      x <- as.numeric(input$one)
      y <- as.numeric(input$two)
      #reactive expression
      n <- x+y
      #your_code_here(3점)
    })
  }
    
 

  # Create Shiny object(3점)
  #your_code_here

#코딩 테스트를 완료하였습니다. 1학기-기말고사-yourname.ipynb로 다운로드받아서 LMS에 과제물로 제출해주십시오.
#수고 하였습니다!